services:
  app:
    image: rag-agent:latest
    ports:
      - "8000:5000"
    volumes:
      - ./:/app
    environment:
      - LANGSMITH_API_KEY=<YOUR_API>
      - TAVILY_API_KEY=<YOUR_API>
      - GROQ_API_KEY=<YOUR_API>
